### PR TITLE
Fix Configuration Reset on Update

### PR DESCRIPTION
**Pull request by mrkalchemy**
This is a proposed solution to issue #52 (https://github.com/slabbi/uddeIM/issues/52).

### CODE REVIEW

**Comment by slabbi** [comment]
A config.class.php should not be included in the zip.
uddeIM creates a default file when it is started the first time.

**Comment by mrkalchemy** [comment]
That was my initial thought but I discovered that the installer script function uddeIM_com_install() includes the config.class.php file. I'm guessing this is to load the definition for the "uddeimconfigclass" class as this is defined in that file.

**Comment by slabbi** [comment]
Sorry, I did the last changes a very long time ago, so I might have forgotten some issues ;)

**Comment by mrkalchemy** [comment]
Thanks for clearing that up. I feel a little dumb as I've never noticed that backup option before.  :(
I'll go ahead and close the issue and pull request.
Thanks again.

**Comment by joomod** [comment]
I try to add an config backup to the script for the next update
db backup is fine, but I think most users will not think about it before

**Comment by slabbi** [comment]
You can use the uninstall() function (script.php) to create a database backup (you should ask the user if he wants to do otherwise the stored backup will be overwritten which might be the one that the user wants to use later).

And on new installation and update you can check if a backup exists and ask the user to restore it automatically.

**Comment by joomod** [comment]
thank you - I will look

**Comment by slabbi** [comment]
> You can use the uninstall() function (script.php) to create a database backup (you should ask the user if he wants to do otherwise the stored backup will be overwritten which might be the one that the user wants to use later).
> 
> And on new installation and update you can check if a backup exists and ask the user to restore it automatically.

Update:
You could store and restore a second backup in database which is stored and (when it exists) restored automatically. The user can then still access his manual created backup when necessary.
Should be simple to implement.

**Comment by slabbi** [comment]
check "script.php"

`class com_uddeimInstallerScript
{
	function install($parent) {
        echo '<p>' . JText::_('COM_UDDEIM_INSTALL_TEXT') . '</p>';
		uddeIM_com_install();
        // $parent->getParent()->setRedirectURL('index.php?option=com_uddeim');
    }
 
    function uninstall($parent) {
        echo '<p>' . JText::_('COM_UDDEIM_UNINSTALL_TEXT') . '</p>';
    }
 
    function update($parent) {
        echo '<p>' . JText::_('COM_UDDEIM_UPDATE_TEXT') . '</p>';
    }
 
    function preflight($type, $parent) {
        // $type is the type of change (install, update or discover_install)
        echo '<p>' . JText::_('COM_UDDEIM_PREFLIGHT_' . $type . '_TEXT') . '</p>';

        $ver = new JVersion();
		// Installing component manifest file version
		$this->release = $parent->getManifest()->version;
 		// Manifest file minimum Joomla version
		$this->minimum_joomla_release = $parent->getManifest()->attributes()->version;

        if ( version_compare( $ver->getShortVersion(), $this->minimum_joomla_release, 'lt' ) ) {
            JFactory::getApplication()->enqueueMessage('Cannot install uddeIM in a Joomla release prior to '.$this->minimum_joomla_release, 'warning');
            return false;
        }

        if ( $type=='update' ) {
            $oldRelease = $this->getParam('version');
            $rel = $oldRelease . ' to ' . $this->release;
            if ( version_compare( $this->release, $oldRelease, 'lt' ) ) {		// lt/le
                JFactory::getApplication()->enqueueMessage('Cannot upgrade ' . $rel, 'warning');
                return false;
            }
        }
	}
 
    function postflight($type, $parent) {
        // $type is the type of change (install, update or discover_install)
        echo '<p>' . JText::_('COM_UDDEIM_POSTFLIGHT_' . $type . '_TEXT') . '</p>';
    }
	
	function getParam( $name ) {
		$db = JFactory::getDbo();
		$db->setQuery('SELECT manifest_cache FROM `#__extensions` WHERE name = "uddeim"');
		$manifest = json_decode( $db->loadResult(), true );
		return $manifest[ $name ];
	}
	
	function setParams($param_array) {
		if ( count($param_array) > 0 ) {
			// read the existing component value(s)
			$db = JFactory::getDbo();
			$db->setQuery('SELECT params FROM `#__extensions` WHERE name = "uddeim"');
			$params = json_decode( $db->loadResult(), true );
			// add the new variable(s) to the existing one(s)
			foreach ( $param_array as $name => $value ) {
				$params[ (string) $name ] = (string) $value;
			}
			// store the combined new and existing values back as a JSON string
			$paramsString = json_encode( $params );
			$db->setQuery('UPDATE `#__extensions` SET params = ' .
				$db->quote( $paramsString ) .
				' WHERE name = "uddeim"' );
				$db->execute();
		}
	}
}`

**Comment by slabbi** [comment]
And there you have to add code to store / restore a configuration backup.

**Comment by joomod** [comment]
ah, nowunderstand,
but should the code not been better added in the update() function?

**Comment by slabbi** [comment]
uninstall -> do backup no.2
install / update -> restore backup no.2

**Comment by joomod** [comment]
is the uninstall() called if update is executed?

**Comment by joomod** [comment]
I coded a config backup this way (no need to load admin.uddeim.php for database backup)

`if (file_exists($pathtoadmin."/config.class.php")) {  //if update, make backup
        require_once($pathtoadmin."/config.class.php");
        $config = new uddeimconfigclass();
        uddeIMsaveConfig($pathtoadmin, $config, '_old'); 
//admin.includes.php edited to take param '_old' for saving as config.class_old.php
        rename($pathtoadmin."/config.setup.php",$pathtoadmin."/config.class.php");
    } else {
        rename($pathtoadmin."/config.setup.php",$pathtoadmin."/config.class.php");
        require_once($pathtoadmin."/config.class.php");
        $config = new uddeimconfigclass();
    }`

of course package zip will no longer include config.class.php but **config.setup.php**

what do you think?

**Comment by joomod** [comment]
ok, just uploaded v5.3 which includes a config backup (by rename)
and an updated config conversation tool.
also added the option to always safe the config to db

**Pull request closed without merging**
